// AUTO-GENERATED by build.sh — do not edit. Per-program section layout;
// the loader's contract with user.ld.
#![allow(dead_code)]
pub const USER_BASE: usize = 0x400000;
pub mod vfs {
    pub const TEXT_VA:   usize = 0x0000000000400000; pub const TEXT_LEN:   usize = 4096;
    pub const RODATA_VA: usize = 0x0000000000401000; pub const RODATA_LEN: usize = 4096;
    pub const DATA_VA:   usize = 0x0000000000402000; pub const DATA_LEN:   usize = 0;
    pub const BSS_VA:    usize = 0x0000000000402000; pub const BSS_LEN:    usize = 0;
}
pub mod client {
    pub const TEXT_VA:   usize = 0x0000000000400000; pub const TEXT_LEN:   usize = 4096;
    pub const RODATA_VA: usize = 0x0000000000401000; pub const RODATA_LEN: usize = 4096;
    pub const DATA_VA:   usize = 0x0000000000402000; pub const DATA_LEN:   usize = 0;
    pub const BSS_VA:    usize = 0x0000000000402000; pub const BSS_LEN:    usize = 4096;
}
pub mod client_b {
    pub const TEXT_VA:   usize = 0x0000000000400000; pub const TEXT_LEN:   usize = 4096;
    pub const RODATA_VA: usize = 0x0000000000401000; pub const RODATA_LEN: usize = 4096;
    pub const DATA_VA:   usize = 0x0000000000402000; pub const DATA_LEN:   usize = 0;
    pub const BSS_VA:    usize = 0x0000000000402000; pub const BSS_LEN:    usize = 4096;
}
