#!/usr/bin/env bash
# build.sh — two-stage woflOS build.
#   Stage 1: compile the userspace crate (N programs, each linked at 0x400000
#            into its OWN flat blob), extract each program's section layout.
#   Stage 2: build the kernel (embeds the blobs + generated layout).
# RUSTFLAGS is set explicitly so the user build OVERRIDES (not joins) the
# kernel's inherited .cargo/config.toml rustflags — avoiding a doubled -T.
set -euo pipefail
cd "$(dirname "$0")"

TARGET=riscv64gc-unknown-none-elf
SYSROOT="$(rustc +nightly --print sysroot)"
OBJCOPY="$(find "$SYSROOT" -name 'llvm-objcopy' | head -1)"
NM="$(find "$SYSROOT" -name 'llvm-nm' | head -1)"
OBJDUMP="$(find "$SYSROOT" -name 'llvm-objdump' | head -1)"
[ -x "$OBJCOPY" ] || { echo "llvm-objcopy not found (rustup component add llvm-tools)"; exit 1; }

# Extend this as userspace grows (the VFS service joins here at 5.1).
PROGRAMS="vfs client client_b"

echo "== Stage 1: userspace =="
pushd user >/dev/null
RUSTFLAGS="-C link-arg=-Tuser.ld -C link-arg=--no-relax -C relocation-model=static" \
    cargo +nightly build --release --target "$TARGET"
popd >/dev/null

LAYOUT=src/user_layout.rs
cat > "$LAYOUT" << 'RS'
// AUTO-GENERATED by build.sh — do not edit. Per-program section layout;
// the loader's contract with user.ld.
#![allow(dead_code)]
pub const USER_BASE: usize = 0x400000;
RS

sym() { "$NM" "$1" | awk -v s="$2" '$3==s {print "0x"$1}'; }

for prog in $PROGRAMS; do
    ELF="user/target/$TARGET/release/$prog"
    "$OBJCOPY" -O binary "$ELF" "src/$prog.bin"

    ENTRY=$("$OBJDUMP" -f "$ELF" | awk '/start address/{print $NF}')
    [ "$((ENTRY))" -eq "$((0x400000))" ] || { echo "FATAL: $prog entry $ENTRY != 0x400000"; exit 1; }

    TS=$(sym "$ELF" __text_start);   TE=$(sym "$ELF" __text_end)
    ROS=$(sym "$ELF" __rodata_start);ROE=$(sym "$ELF" __rodata_end)
    DS=$(sym "$ELF" __data_start);   DE=$(sym "$ELF" __data_end)
    BS=$(sym "$ELF" __bss_start);    BE=$(sym "$ELF" __bss_end)

    cat >> "$LAYOUT" << RS
pub mod $prog {
    pub const TEXT_VA:   usize = $TS; pub const TEXT_LEN:   usize = $((TE - TS));
    pub const RODATA_VA: usize = $ROS; pub const RODATA_LEN: usize = $((ROE - ROS));
    pub const DATA_VA:   usize = $DS; pub const DATA_LEN:   usize = $((DE - DS));
    pub const BSS_VA:    usize = $BS; pub const BSS_LEN:    usize = $((BE - BS));
}
RS
    echo "  $prog: entry=$ENTRY text=$((TE-TS))B rodata=$((ROE-ROS))B data=$((DE-DS))B bss=$((BE-BS))B"
done

echo "== Stage 2: kernel =="
cargo +nightly build --release --target "$TARGET"
echo "Build OK -> target/$TARGET/release/woflos"
